### ISSUE TITLE
using 2 workspaces watson 

### ISSUE THREAD

**Issue by chakir-alaoui** [watson-developer-cloud/botkit-middleware#100]
i want to  identify the input language and then in my backend select the specific workspace to keep the conversation, but i can't switch to the other workspace.

after detecting user language , i export it with module.exports.language to my app.js but when i use console.log to display the language : language   undefined

Please suggest the best approach to achieve this.

**Comment by chakir-alaoui** [comment]
to detect the language , i'm using a regular expression in bot-facebook.js. if arabic i use module.exports.language='arabic' else module.Exports.language='french'. 
then in my app.js i get the languageand i use if/then to send my bot to the right workspace.

I tried also middleware.before to do the same thing but the bot doesn't reply anymore , below you will find my code in the middleware.before :

  middleware.before = function(message, conversationPayload, callback) {
    var Facebook = require('./bot-facebook');
	var arregex =/[\u0600-\u06FF]/;
	
	console.log(arregex.test(message.text));
	if (arregex.test(message.text)==true){
	Facebook.controller.middleware.receive.use(middleware2.receive);
	}
	else {
	Facebook.controller.middleware.receive.use(middleware.receive);
	
	}
  
  
    callback(null, conversationPayload);
  }

Do you have any other suggestions to help me.

**Comment by aarora91** [comment]
Hi @chakir-alaoui,

I believe you don't need to change the receive middleware based on the language.
All you'd have to do is change the way you're initializing the middleware object (in app.js)

Just change the `workspace_id` based on the result of your regex eval and use it for initializing the middleware obj like it's done here: https://github.com/watson-developer-cloud/botkit-middleware/blob/master/examples/multi-bot/app.js#L22

Let me know if that didn't help or you need more info.
Good luck!

**Comment by chakir-alaoui** [comment]
hi @aarora91 ,

thank you for your reply.
to evaluate my regex expression , i need user text , so the evaluation must be done in the middleware.before or in bot-facebook.js .

i changed just the worksapce-id in my middleware.before but it doesn't work, the bot reply just in french , below you will find my middle.before :  
```js
 middleware.before = function(message, conversationPayload, callback) {
  var Facebook = require('./bot-facebook');
  var arregex = /[\u0600-\u06FF]/;
    console.log(arregex.test(message.text));
    if (arregex.test(message.text)==true){
	Facebook.controller.middleware.workspace_id= process.env.WORKSPACE_ID_Arabic;
	}
	else {
	Facebook.controller.middleware.workspace_id= process.env.WORKSPACE_ID;
	}
	
  
 callback(null, conversationPayload);
}
  ```
what should i do ? am I doing something wrong ?

**Comment by aarora91** [comment]
Ah I see. Then you're right, it must be done before the message is sent to Conversation. Did you try re-initializing the `middleware.conversation` object inside `middleware.before` function?
If you over-write it there with the appropriate workspace_id it should pick it up when `postMessage` is invoked.
Give that a try..also if you run the code with the debug string 'watson-middleware:index' then it should print all debug statements inside https://github.com/watson-developer-cloud/botkit-middleware/blob/master/lib/middleware/index.js

**Comment by chakir-alaoui** [comment]
how can i initialize the middleware.Conversation inside middleware.before ?? and how can i run the code with debug mode ?

**Comment by chakir-alaoui** [comment]
@aarora91, 
i'm running my code now with the debug mode, and i changed the middleware.before like this :   
```js 
 middleware.before = function(message, conversationPayload, callback) {
  var Facebook = require('./bot-facebook');
  var arregex = /[\u0600-\u06FF]/;
    console.log("user message   : " + message.text);
    console.log("test regex : " + arregex.test(message.text));
    if (arregex.test(message.text)==true){
	Facebook.controller.middleware.workspace_id= process.env.WORKSPACE_ID_Arabic;
	}
	else {
	Facebook.controller.middleware.workspace_id= process.env.WORKSPACE_ID;
	}
	console.log("workspaceid " +Facebook.controller.middleware.workspace_id);
        //Facebook.controller.middleware.receive.use(middleware.receive);
 callback(null, conversationPayload);
}
```
the output show that the workspace_id is changed based on user input but the bot reply only in french,below you will find the ouput : 
```
OUT user message   : Cava ?
OUT test regex : false
OUT workspaceid 5183ce8exxxxxxxxxxxx
OUT debug: RECEIVED MESSAGE
OUT debug: CUSTOM FIND CONVO 1439418016150021 1439418016150021
OUT debug: I HEARD [ '(.*)' ]
OUT user id test 1439418016150021
OUT debug: WEBHOOK SUCCESS { recipient_id: '1439418016150021',
OUT   message_id: 'mid.$cAACg7Sn_YgFlGq-tj1e6WplbL05g' }
     OUT [2017-10-04T22:03:38.386+0000] "POST /facebook/receive HTTP/1.1" 200 313 2 "-" "-" "108.168.250.153:44636" "169.47.199.73:61476" x_forwarded_for:"31.13.110.111" x_forwarded_proto:"https" vcap_request_id:"7d482f0c-b57e-4d67-4109-92af4099c500" response_time:0.008082314 app_id:"8fbf4181-3598-40e3-a273-34ba08229866" app_index:"0" x_global_transaction_id:"4010962105" true_client_ip:"-" x_b3_traceid:"fcbfee19d5ef521f" x_b3_spanid:"fcbfee19d5ef521f" x_b3_parentspanid:"-"
OUT user message   : Cava :D
OUT test regex : false
OUT workspaceid 5183cexxxxxxxxxxxxxxxxxxxxxxxx
OUT debug: RECEIVED MESSAGE
OUT debug: CUSTOM FIND CONVO 1439418016150021 1439418016150021
OUT debug: RECEIVED MESSAGE
OUT debug: CUSTOM FIND CONVO 176940106140994 176940106140994
OUT debug: RECEIVED MESSAGE
OUT debug: CUSTOM FIND CONVO 1439418016150021 1439418016150021
OUT user message   : سلام
OUT test regex : true
OUT workspaceid 4af51yyyyyyyyyyyyyyyyyyyyyyyyyyy
```
when i add Facebook.controller.middleware.receive.use(middleware.receive); to my middleware.before, the bot doesn't reply.

Do you have any other suggestions to help me ?
