### ISSUE TITLE
Is  'minimum-confidence' working as a parameter to 'watson-middleware' constructor?

### ISSUE THREAD

**Issue by pgoldweic** [watson-developer-cloud/botkit-middleware#104]
I assumed that by including a 'minimum-confidence' parameter value of 0.5, watson would not return intents that have a confidence value of 0.3 to the bot, however, that is what seems to be going on in my case. Is this parameter actually working, or have I misunderstood the meaning of it?

**Comment by Naktibalda** [comment]
It is used by hears method.

**Comment by pgoldweic** [comment]
Oh, I see. So it looks like my understanding was incorrect. Could you be a little bit more explicit as to how it is used by the 'hears' method? I am not clear as to whether this is Watson-related at all or not. Thanks!

**Comment by Naktibalda** [comment]
[documentation](https://github.com/watson-developer-cloud/botkit-middleware#intent-matching) and [code](https://github.com/watson-developer-cloud/botkit-middleware/blob/v1.5.0/lib/middleware/index.js#L40-L53) of `hear`.

Searching for `minimum_confidence` in watson sdk produces [no results](https://github.com/watson-developer-cloud/node-sdk/search?utf8=%E2%9C%93&q=minimum_confidence&type=), so this setting has no effect on Watson Conversation.

**Comment by pgoldweic** [comment]
Ok, thanks for clarifying this.

**Comment by germanattanasio** [comment]
The question was answered so I'm closing this for now
