### ISSUE TITLE
Problem with Facebook

### ISSUE THREAD

**Issue by pelolisu** [watson-developer-cloud/botkit-middleware#109]
I do not know why but the messages are not coming in the middleware. I've checked everything, the credentials, the tunnel. When I registered the callback url on facebook webhook it showed that everything is ok. But if I send a message on facebook it the bot is not triggered. I put breakpoint in code in debug mode and nothing happens.  Following the image of the service:
![image](https://user-images.githubusercontent.com/11825770/31580267-d73de4dc-b120-11e7-8bfc-306d361ebb68.png)
And the status of the ngrok that displays the request. No new requests are made when a user's message is sent via Facebook.
![image](https://user-images.githubusercontent.com/11825770/31580285-3ccd42d4-b121-11e7-8d86-f27cbd978ea7.png)

I used the multi-bot example

**Comment by yam-inglab** [comment]
Hi There, I have exactly the same issue , how did you resolve the problem ?

**Comment by pelolisu** [comment]
Remember to subscribe your webhook on a facebook page in the Messenger menu on the development page. Try again
