### ISSUE TITLE
Is Botkit middleware only for testing?

### ISSUE THREAD

**Issue by ehaynie63** [watson-developer-cloud/botkit-middleware#110]
Hi!

So I've gotten my chatbot live on FB messenger but it goes offline when I close my command prompt window. I'm new to programming, I'm guessing that my local host server quits so I can't keep using the bot. What am I supposed to do to keep it running?

Thanks!

-Elizabeth

**Comment by Naktibalda** [comment]
Use [forever](https://www.npmjs.com/package/forever) or some similar tool.

**Comment by germanattanasio** [comment]
closing this as it wasn't a bug
