### ISSUE TITLE
Watson Conversation did not reply to message at group direct message channel in slack

### ISSUE THREAD

**Issue by Hikotoshi** [watson-developer-cloud/botkit-middleware#114]
I used multi-bot, when executing npm start, the slack bot implementing Watson conversation  replied to me when I input some message normaly in single direct message channel.
However, when I made a directmessage group channel with more than 2 people including the bot, 
the bot did not reply to any input message.

the Log on the console seemesthat it recognized new input even in the directmessage group channel,
showing
info: Warning: using temporary storage. Data will be lost when process restarts.

but the bot did not reply response to any input message.

Does anybody can help me how to solve this issue, I want to make the bot active speaking even in the
directmessagegroup channel

**Comment by Naktibalda** [comment]
A better place to report slack issues is https://github.com/howdyai/botkit/issues

**Comment by Hikotoshi** [comment]
I think this is not slack issue, depending on the implement method of botkit-middleware,
Maybe it recognize the input of direct message type but not recognize the input of group direct message type.

**Comment by Naktibalda** [comment]
Example is not a part of implementation.

I think that it is a very bad idea to use these examples as a basis for your project.
It would be much better to use https://github.com/howdyai/botkit-starter-slack/ and replace Botkit Studio integration with Watson middleware.

However if message.type is not one of listed in `slackController.hears(['.*'], ['direct_message', 'direct_mention', 'mention'],` then it is obvious why you don't get a response, check what it is and modify accordingly.
