### ISSUE TITLE
Fatal TypeError: Cannot read property 'output' of undefined

### ISSUE THREAD

**Issue by ricagurgel** [watson-developer-cloud/botkit-middleware#116]
Hi everyone.

The problem: User input with /n crashes node. How to prevent this?

...."watsonError":{"cause":{"code":400,"error":"Invalid Request Body","errors":[{"message":"text can not contain the following characters: tab, new line, carriage return.","path":".input.text"....

**Comment by ricagurgel** [comment]
If think isn't big deal.

just insert line line 90 at botkit-middleware/index.js
      	message.text = message.text.replace(/(\r\n|\n|\r)/gm," ");
  
I'm right?

**Comment by Naktibalda** [comment]
You should be able to modify message.text using before hook: https://github.com/watson-developer-cloud/botkit-middleware#before-and-after

**Comment by Naktibalda** [comment]
@ricagurgel to avoid fatal error mentioned in the subject, you have to check message.watsonError before using message.watsonData.

We have an example at https://github.com/watson-developer-cloud/botkit-middleware/blob/master/examples/simple-bot/simple-bot-slack.js#L37-L39

**Comment by ricagurgel** [comment]
Hi @Naktibalda Actually I sent the contribution suggesting server.js line 90 change (as mentioned above)  and the staff accepted it and it is already changed. 

No more issues when users send invalid characters for every developer here. So glad to contribute. 😀 Thanks.

**Comment by Naktibalda** [comment]
It is possible that Conversation can return some other error, so it is better to be safe.
