### ISSUE TITLE
problem in Watson response after changing botkit storage module

### ISSUE THREAD

**Issue by pgoldweic** [watson-developer-cloud/botkit-middleware#121]
I've just changed the storage module that my bot is using from json file store to botkit-storage-dynamodb (this npm module is available on github), and I started seeing an error returned from Watson as follows:

ValidationException: ExpressionAttributeValues contains invalid value: Input collection contains duplicates for key 
```
:context {"cause":{"message":"ExpressionAttributeValues contains invalid value: Input collection contains duplicates for key :context","code":"ValidationException","time":"2017-12-18T21:34:39.246Z","requestId":"ABJ7VT1PB7JBUDVQAFSF9M210BVV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":false,"retryDelay":18.287361752594443},"code":"ValidationException","time":"2017-12-18T21:34:39.246Z","requestId":"ABJ7VT1PB7JBUDVQAFSF9M210BVV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":false,"retryDelay":18.287361752594443}
```
I'm unclear as to what is causing this error. In my bot, I save the ongoing conversation (between a bot an a user, via direct messages) in channel storage, and I don't explicitly save or retrieve anything from user storage. The bot was working fine before the storage switch (it's running in Spark). 
Any ideas on where the problem could be?

**Comment by Naktibalda** [comment]
Try to log payload in before hook and see if context looks wrong in some way.

**Comment by pgoldweic** [comment]
I actually logged the 'message' variable before the call to WatsonInterpret, and I get the following:

Sending message to Watson:  { user: 'pgoldweic@northwestern.edu',
  channel: 'Y2lzY29zcGFyazovL3VzL1JPT00vZmNmOTViZWQtZjlhYS0zMGZlLWFiZjMtODRjMTM5ZDQ2MTVk',
  text: 'how do I add a student to my course?',
  id: 'Y2lzY29zcGFyazovL3VzL01FU1NBR0UvMzhmNGNjMjAtZTQzYi0xMWU3LWE2ZDctMjM5Y2ZjYmU1NzFi',
  original_message:
   { id: 'Y2lzY29zcGFyazovL3VzL01FU1NBR0UvMzhmNGNjMjAtZTQzYi0xMWU3LWE2ZDctMjM5Y2ZjYmU1NzFi',
     roomId: 'Y2lzY29zcGFyazovL3VzL1JPT00vZmNmOTViZWQtZjlhYS0zMGZlLWFiZjMtODRjMTM5ZDQ2MTVk',
     roomType: 'direct',
     text: 'how do I add a student to my course?',
     personId: 'Y2lzY29zcGFyazovL3VzL1BFT1BMRS82MjBlNWQ5Ny1kMzE0LTQzZmEtYjYxOC05ODEwOGQ4YWMzZDE',
     personEmail: 'pgoldweic@northwestern.edu',
     created: '2017-12-18T21:34:26.786Z',
     orgId: 'Y2lzY29zcGFyazovL3VzL09SR0FOSVpBVElPTi9iYTA0MjUwYi02MWM3LTRmMGEtOGVlYy01MmFlMDQ2MzVkYjg' },
  match:
   [ 'how do I add a student to my course?',
     index: 0,
     input: 'how do I add a student to my course?' ] }


The above doesn't even mention the 'context'. I wonder if it may have something to do with the users storage (which I'm not explicitly using in my code at all) which may be something that Watson relies on?

**Comment by Naktibalda** [comment]
You logged the message before context was added to it.
Look at example of before hook and log payload there: https://github.com/watson-developer-cloud/botkit-middleware/blob/master/README.md#before-and-after

**Comment by pgoldweic** [comment]
Yes, you are right. I just added a console.log statement within a watsonMiddleware.before method, and this is what I got:

ConversationPayload is:  { workspace_id: '1477e470-93ae-49e2-a659-1dae97c12837',
  input: { text: 'how do I add a student to my course?' },
  context:
   { failedUnderstanding: 1,
     allIntents: [],
     system:
      { dialog_request_counter: 2,
        dialog_stack: [Object],
        dialog_turn_counter: 2,
        _node_output_map: [Object],
        branch_exited: true,
        branch_exited_reason: 'completed' },
     conversation_id: 'c0c500bf-d3a7-4ff7-aa6b-81674ca0e97b' } }
Warning: Watson error received!: ValidationException: ExpressionAttributeValues contains invalid value: Input collection contains duplicates for key :context {"cause":{"message":"ExpressionAttributeValues contains invalid value: Input collection contains duplicates for key :context","code":"ValidationException","time":"2017-12-18T23:30:57.230Z","requestId":"MAU4Q9EIH7T8B1JU6SGDQJKA9NVV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":false,"retryDelay":3.9042008275380624},"code":"ValidationException","time":"2017-12-18T23:30:57.230Z","requestId":"MAU4Q9EIH7T8B1JU6SGDQJKA9NVV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":false,"retryDelay":3.9042008275380624}

I don't see anything odd in that payload. Do you?

**Comment by Naktibalda** [comment]
It looks good to me too.
This error is probably coming from dynamo, log conversation response in after hook to check if you got a successful response from Watson.

**Comment by pgoldweic** [comment]
Turns out that the AFTER hook never gets executed apparently (no printout is found). The last thing I see from Watson is the error message I posted in my first email :-(.

**Comment by pgoldweic** [comment]
Could this have something to do with what Watson expects to find in the user context instead? (thinking that the 'context' is actually stored in there, isn't it?) I am not manipulating the context myself, but I wonder if this might be what Watson complains about.

**Comment by pgoldweic** [comment]
I have to correct myself, sorry!. I actually see that the AFTER hook runs also, and displays this payload right before the error message (by Watson) is printed out: 

ConversationPayload AFTER is:  { intents:
   [ { intent: 'user-enrollment-ses',
       confidence: 0.9265775203704834 } ],
  entities: [],
  input: { text: 'I can\'t find a class that I should be enrolled in' },
  output:
   { text:
      [ 'Sure, I\'ll be happy to help. Hope you don\'t mind me asking you for some information.',
        'Could you tell me what is your academic role, and also describe for me the course you are having issues with?' ],
     nodes_visited:
      [ 'node_1_1506885954983',
        'node_3_1512763379204',
        'user-enrollment-SES',
        'handler_5_1500328523645',
        'user-enrollment-SES' ],
     log_messages: [] },
  context:
   { allIntents: [],
     conversation_id: '694368ec-17aa-42ea-9971-43dc91eb9bfb',
     system:
      { dialog_request_counter: 2,
        dialog_stack: [Object],
        dialog_turn_counter: 2,
        _node_output_map: [Object] } } }

**Comment by Naktibalda** [comment]
This ticket should be closed because it is an issue of dynamodb
https://github.com/joshuahoover/botkit-storage-dynamodb/issues/4

**Comment by pgoldweic** [comment]
It is actually an issue with the 'dynasty' npm module that the storage module is using to interact with Dynamo DB, not of Dynamo itself. You can go ahead and close the ticket though. Thanks for your help!
