### ISSUE TITLE
How much memory your deployed API are using?!

### ISSUE THREAD

**Issue by ricagurgel** [watson-developer-cloud/botkit-middleware#124]
It's not really a issue. It's just an ask.

My very simple API are using about 51-62 MB

Seems okay?

Thanks

**Comment by germanattanasio** [comment]
I would recommend you at least 128MB. From what I've seen during the deployment you may use up to 80MB and then it will go down to 68MB. It all depends on your application.

I'm closing this since it's not an issue with the library.
