### ISSUE TITLE
Slac bot will not work after hosting code in Bluemix

### ISSUE THREAD

**Issue by monesh-pattar** [watson-developer-cloud/botkit-middleware#128]
The application perfectly works in local. When I hosted the app in Bluemix, the bot stopped working in slack. Are there any additional setting when we host in Bluemix? Please share the steps. When I hosted the code in bluemix, the build succeded, but the slac bot does not respond. Sometimes I got the error:
Classification Error: No response received. Please try again.'

Need Help!!

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps. Check the CONTRIBUTING.md for an example.

**Comment by monesh-pattar** [comment]
1. Copied the code in my app from https://github.com/watson-developer-cloud/botkit-middleware/tree/master/examples/simple-bot
2. Created bot in slack and added the token to above codebase
3. Tested the bot the in slack.. works perfectly
4. Deployed the code to bluemix , the build succeeded without any errors
5. Bot in slack not able to send/receive messages

**Comment by monesh-pattar** [comment]
The app worked properly. I deleted and hosted the app again
