### ISSUE TITLE
Call some external service before/after calling Conversation

### ISSUE THREAD

**Issue by jersonjunior** [watson-developer-cloud/botkit-middleware#13]
It is possible stores the text entries in variables and run script in bash after the return of any command. example:
You can order a soda or a juice?
juice
You can order pizza or a sandwich?
Pizza
script:
/opt/order.sh "juice" "pizza"

**Comment by aarora91** [comment]
Yes, you can add the code for running `/opt/order.sh "juice" "pizza"` in the _after_ function in your app.js(or whatever calls the middleware).
See https://github.com/watson-developer-cloud/botkit-middleware/blob/master/examples/multi-bot/app.js#L45

You would have to check the watsonResponse payload to know when to make that external service request so it would look something like this:

```js
middleware.after = function(message, conversationResponse, callback) {
  if(conversationResponse.context.flag){
   // Call your service here.
    postOrder(["juice", "pizza"]);
  }
  callback(null, conversationResponse);
  }
```

In your Watson Conversation workspace, define a context variable "flag" which will indicate when to place your order. This will be sent back in the response payload. Your node JS app will simply check if flag is set and make the appropriate external service request.

**Comment by jersonjunior** [comment]
Hello, 
I had success using hears the running external scripts:

//Spotify
slackController.hears(['Play spotify music'], ['direct_message', 'direct_mention', 'mention'], function(bot, message) {
  slackController.log('Slack message received');
  bot.reply(message, message.watsonData.output.text.join('\n'));
 // now do something special related to the hello intent
function puts(error, stdout, stderr) { sys.puts(stdout) }
exec("nodejs /home/volumio/spotify.io", puts);

However I still can not use the after function, not sure what to do in the dialog to use a context with variable flag, could of a light?

middleware.after = function(message, conversationResponse, callback) {
  if(conversationResponse.context.flag){
   // Call your service here.
   function puts(error, stdout, stderr) { sys.puts(stdout) }
exec("nodejs /home/volumio/spotify.io", puts);
  }
  callback(null, conversationResponse);
  }

**Comment by stevenoh93** [comment]
I've followed up on this on #14
