### ISSUE TITLE
How do i use socketbot with watson conversation

### ISSUE THREAD

**Issue by Developer-sa** [watson-developer-cloud/botkit-middleware#130]
Hi
I want to know how i can use socketbot without botkit studio token. I am using botkit with watson and facebook as thirdparty now, would like to know how i can receive and send messages that i was doing using facebookbot through socketbot. So, instead of facebook, i want to get the watson responses on my web application now.
Any help would be appreciated. Thanks

**Comment by Naktibalda** [comment]
Use https://github.com/howdyai/botkit-starter-web and replace Botkit Studio integration code with Watson integration code that you can find in the README file.

**Comment by Developer-sa** [comment]
Did you mean this, 
var bot_options = {
    username: process.env.CONVERSATION_USERNAME,
    password: process.env.CONVERSATION_PASSWORD,
    workspace_id: process.env.WORKSPACE_ID,
    url: process.env.CONVERSATION_URL,
    version_date: process.env.CONVERSATION_VERSION_DATE
    replyWithTyping: true,
};

Thanks

**Comment by Naktibalda** [comment]
Yes, options are necessary, but you have to create middleware object and register it with Botkit (as in example).
And don't forget to install botkit-middleware-watson using npm.

**Comment by Developer-sa** [comment]
Thanks much, it works.
Can I also know more about message filtering? I don't clearly understand what can i use it for? Can i use it to do something like this, when a particular intent is triggered, i don't want it to go back to watson and get outputs, rather I would like to do it inside my code.

Thanks in advance

**Comment by Naktibalda** [comment]
> Can I also know more about message filtering? I don't clearly understand what can i use it for? 

Some chat services send technical messages that don't include input from the user, message filtering allows to avoid sending such messages to the service.

> Can i use it to do something like this, when a particular intent is triggered, i don't want it to go back to watson and get outputs, rather I would like to do it inside my code.

No. Message filtering filters messages comming from the user.
Sending response from your code is actually simpler than going back to watson.

https://github.com/watson-developer-cloud/botkit-middleware#intent-matching
```js
slackController.hears(['intent-name'], ['direct_message', 'direct_mention', 'mention'], watsonMiddleware.hear, function(bot, message) {
  bot.reply(message, 'Hardcoded message here');
});
```

**Comment by pgoldweic** [comment]
Wouldn't the above simply filter based on the actual text entered by the user? If you want to recognize actual Watson intents, then you should look at the results obtained from Watson middleware (that is, the message gets augmented with all the information that Watson extracted, including intents). Then you could decide, in your logic, if you want to actually use the Watson-produced response, (which is also part of the augmented message) or provide your own or not.

**Comment by Developer-sa** [comment]
How can I directly take user inputs from a channel, say facebook, for a particular topic instead of passing it to watson middleware when I have watson middleware for other intents in my code?
I want to have a conversation without sending it to watson.

Thanks

**Comment by pgoldweic** [comment]
As far as I understand it, you need to use a middleware wrapper, as explained in the readme file (see section on message filtering). That is, you write your own function that decides when/how to pass the message to the Watson middleware (or not).

**Comment by Developer-sa** [comment]
Thank you so much. That helps a lot.
Can i build an entire conversation using this message filtering?

Thanks

**Comment by Developer-sa** [comment]
Thanks a lot
