### ISSUE TITLE
Botkit anywhere - help

### ISSUE THREAD

**Issue by ca42rico** [watson-developer-cloud/botkit-middleware#139]
Hi,
I used this this fantastic middleware for a Facebook Messenger bot.
Now I would like to connect it to an mobile app, how can I do? Where should I connect the middleware to the websocket?
Thank you

**Comment by Naktibalda** [comment]
same place.

**Comment by ca42rico** [comment]
Thanks you for your reply.
Could you show me how to do it?
Is something like:
In app.js
`if (process.env.USE_WEBSOCKET) {...}`
Thanks

**Comment by Naktibalda** [comment]
take the botkit-starter-web and copy watson initialization code and `controller.middleware.receive.use(watsonMiddleware.receive);` from your previous project.

This line of code connects middleware to botkit.

**Comment by germanattanasio** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs.
