### ISSUE TITLE
Watson - Developer

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/botkit-middleware#14]
Hi,
I wonder if Watson can work only with JavaScript to develop within the Conversation code that will store data in a variable and run a script.

Thanks.

**Comment by germanattanasio** [comment]
Can you please elaborate your question? Maybe with an example.

**Comment by sayurimizuguchi** [comment]
Ex:
variable ("comando", "cmd");

function(message, conversationResponse, callback) { 
if(conversationResponse.context.flag)
{ // Call your service here. 
postOrder(["cmd comando", "comando"]); } 
callback(null, conversationResponse); } (Script: execute: c:\windows\system32\cmd.exe

**Comment by jersonjunior** [comment]
I have the same question, after the user enters something like pizza then in running the script as shown below:

var sys = require('sys');
var exec = require('child_process').exec;
 
function puts(error, stdout, stderr) { sys.puts(stdout) }
exec("date > /root/date.txt", puts);

According to the subject # 13 must use context flag in the dialog but do not know how to do it. Could you give practical examples of how this can be

**Comment by sayurimizuguchi** [comment]
I want developer one page for integration with Watson and conversation with users 


Example:

//variables Watson
{
  "intents": [],
  "entities": [],
  "input": {},

// questions in conversation
"output": {
    "log_messages": [],
    "text": [
      "Olá, posso ajudar em algo? "
    ],
    "nodes_visited": [
      "nodexxxx"
    ]
  },

//id conversation for integrate
  "context": {
    "conversation_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "system": {
      "dialog_stack": [
        "root"
      ],
      "dialog_turn_counter": 1,
      "dialog_request_counter": 1
    },
    "default_counter": 0
  }
}

// ADD MUST Take JSON
var pizza = output.text; 


// after the watson say idk

"output": {
    "log_messages": [],
    "text": [
      "Qual sabor da sua pizza? "

// ADD MUST Take JSON

var sabor = output.text; 

// after this, the watson reconigze the taste pizza and execute one command for request the pizza, example:


middleware.after = function(message, conversationResponse, callback) {
if(conversationResponse.context.flag){

 // Call your service here. 

postOrder(["juice", "pizza"]); 
} 
callback(null, conversationResponse); }

**Comment by stevenoh93** [comment]
@jersonjunior You can follow this [documentation](http://www.ibm.com/watson/developercloud/doc/conversation/advanced_overview.shtml#advanced_context) to learn more about context variables. In short, you can use the [tooling](https://www.ibm.com/watson/developercloud/doc/conversation/convo_usetooling.shtml) to easily set boolean flags in the context variable

@sayurimizuguchi I'm not sure if I am understanding your question, but I think you can also benefit from reading the documentation that I linked above on manipulating context variables
