### ISSUE TITLE
App is taking lot of memory

### ISSUE THREAD

**Issue by rajeevsh01** [watson-developer-cloud/botkit-middleware#145]
When I am deploying the multibot app for Facebook messenger it is taking more than 1024MB and failing as I don't have more memory allocated to my account. Is there any way I reduce it?

**Comment by Naktibalda** [comment]
It doesn't look like an issue of middleware, a better place to report this issue is the main botkit repo: https://github.com/howdyai/botkit/issues

**Comment by peterswimm** [comment]
How many bots are you deploying? The logical limit for multiple bots is largely memory, but a single instance should be able to support thousands of bots.

**Comment by germanattanasio** [comment]
There hasn't been much activity on it which makes me think it was a problem in @rajeevsh01's code. Closing, but please re-open if it still occurs.
