### ISSUE TITLE
'quick replies' with this middleware and botkit anywhere: any examples?

### ISSUE THREAD

**Issue by pgoldweic** [watson-developer-cloud/botkit-middleware#147]
I'd like to see an example that uses botkit anywhere, with this Watson middleware and quick replies. Can somebody point to one?

**Comment by Naktibalda** [comment]
This is content of a node with quick replies in JSON editor:
```json
{
  "output": {
    "text": [
      "Hi, I'm the chatbot.",
      "How can I help you today?"
    ],
    "quick_replies": [
      {
        "title": "Task 1",
        "payload": "task 1"
      },
      {
        "title": "Task 2",
        "payload": "task 2"
      }
    ]
  }
}
```

**Comment by pgoldweic** [comment]
Thanks @Naktibalda for providing this! What's not clear to me is whether the bot function sendRepliesToUser is already part of this middleware or not. I have been using an old version (1.4.0).

**Comment by pgoldweic** [comment]
I now see that this function is *not* yet part of the middleware and that I'd have to include it myself in my bot application. Given the older versions that I am using (botkit anywhere 0.01 and watson middleware 1.4.0), would I need to rebuild in order to be able to use the function above?

**Comment by Naktibalda** [comment]
Older versions of Botkit web starter kit used `message.attachments.quickReplies` structure, I actually modified my code to match the current client side code.

JavaScript code is my wrapper for both.reply, you don't have to use it all,
The important part is `message.quickReplies = message.watsonData.output.quick_replies;`

**Comment by pgoldweic** [comment]
I see. Thanks again for your reply @Naktibalda . It's been very helpful!

**Comment by germanattanasio** [comment]
Closing since the question was addressed by @Naktibalda
