### ISSUE TITLE
How connect to whatsapp bussines

### ISSUE THREAD

**Issue by CamiloB** [watson-developer-cloud/botkit-middleware#149]
Hi i want to connect my watson assitant to my whatsapp bussiness, can you please tell me what a i need to do im new whit this so thats why im asking to general

**Comment by mitchmason** [comment]
WhatsApp business for bots is still in beta, so you'll need to get into their beta program to get access to the apis, and then build the orchestration yourself similar to how any number of orchestrators work. We have written a Botkit middleware to connect to Botkit which connect to multiple channels (not WhatsApp, but maybe you can get inspiration there)

But first you need to go through whatsapps beta program.

**Comment by CamiloB** [comment]
Ok thanks a lot i already sing up to this program ill wait the response ill give you updates if they get me into it.

**Comment by germanattanasio** [comment]
@CamiloB as @mitchmason said. If botkit supports whatsapp business then we just need to update version of botkit we use here and it will be supported. It's not different than other channels like Facebook or slack for us
