### ISSUE TITLE
How can I connect Watson and facebook using only botkit, not botkit-middleware-watson

### ISSUE THREAD

**Issue by SaziyaBanu** [watson-developer-cloud/botkit-middleware#150]
Hi,

I have already used botkit-middleware-watson, it's great. Now what I would want to know is how can i send facebook messages to watson and back and forth using just botkit, not the middleware.

Thanks in advance

**Comment by Naktibalda** [comment]
It's an odd question to ask.
Why do you want to avoid using middleware?

**Comment by SaziyaBanu** [comment]
Dear Naktibalda,

It's a business requirement. Can you please let me know if it is achievable or not? If yes, please provide an example

Thanks in advance

**Comment by Naktibalda** [comment]
A business requirement to connect Botkit to Watson Assistant without using this middleware?
Your best option is to clone and rebrand it.
Or you can start from scratch.

Are you allowed to use [watson-node-sdk](https://www.npmjs.com/package/watson-developer-cloud)?

**Comment by SaziyaBanu** [comment]
Thing is that we can replace watson with something else anytime. Hope this helps.

Thanks in advance

**Comment by Naktibalda** [comment]
Ah, you want abstraction.

In that case, you can still use this middleware, but you must avoid using any Watson specific properties of the message and avoid calling any methods of middleware.

The only Watson specific thing that you can't avoid using is `message.watsonData.output.text`,
You could write your own wrapper for this middleware and all other middlewares that you want to support to transform response to common format.

**Comment by SaziyaBanu** [comment]
Can you please elaborate on how I can do it? I am not getting a clear idea.

Thanks

**Comment by Naktibalda** [comment]
I am using example of middleware wrapper from https://github.com/watson-developer-cloud/botkit-middleware#using-middleware-wrapper

So it would look like this:
```js
var watsonWrapper = function (bot, message, next) {
  watsonMiddleware.receive(bot, message, function() {
      if (message.watsonData.output.text) {
          message.replyText = message.watsonData.output.text.join('\n');
      }
      next();
  })
};

// here you tell botkit which wrapper to use
slackController.middleware.receive.use(watsonWrapper);

// and this part is independent of NLP middleware
slackController.hears(['.*'], ['direct_message', 'direct_mention', 'mention'], function(bot, message) {
  if (message.replyText) {
    bot.reply(message, message.replyText);
  }
});
```

You would have to implement wrappers for other NLP middlewares too to assign response to message.replyText.
It is up to you to do that and to test this code.

**Comment by germanattanasio** [comment]
Closing since this is not a problem with this library or a question related to Watson Assistant
