### ISSUE TITLE
Watson Conversation V1 is deprecated, needs updating to V2

### ISSUE THREAD

**Issue by NyWn** [watson-developer-cloud/botkit-middleware#151]
Error occuring when creating a new Watson Assistant instance as an old API version is being used:

`ERR WARNING: Conversation V1 is deprecated and will be removed in the next major release of the SDK. Use Assistant V1 or Assistant V2. Set {silent: true} to disable this message.`

Looks like its because of:

https://github.com/watson-developer-cloud/botkit-middleware/blob/231815c76d3092dd829ad346e87a474486838aed/lib/middleware/index.js#L19

Here's the docs for the latest version:

https://www.npmjs.com/package/watson-developer-cloud#assistant-v2

**Comment by pgoldweic** [comment]
Could somebody please explain how this is supposed to affect bots in production? I have one using version 1.4.0 of the middleware. Thanks!

**Comment by yaliagap** [comment]
Is there any news for the botkit update and now the SDK Assistant is used?

**Comment by mitchmason** [comment]
I dont see how these two are related...
Botkit middleware calls the /message API for an already created instance. It does not create an instance of Assistant. 
Anything in production will continue to use the v1 api, which is not deprecated. We are releasing a v2 which will include new features, but v1 is not deprecated if you still want to work that way.

**Comment by pgoldweic** [comment]
@mitchmason, if the v1 api is not deprecated, why did @NyWn see the error message?

**Comment by mitchmason** [comment]
bot kit middleware does not create a new instance, so I'm not sure. I'd want to hear more about what they were doing and where in the process that happened

**Comment by yaliagap** [comment]
bot kit middleware itself creates a conversation instance.

botkit-middleware/lib/middleware/index.js
Line 19 in 231815c
 var ConversationV1 = require('watson-developer-cloud/conversation/v1'); 

It is precisely in this file and line where a conversation object v1 is instantiated. That is why the warning message is displayed.

**Comment by mitchmason** [comment]
Im pretty sure that just pulls in the sdk, it does not create a new service instance. Maybe the error message wording is just funky.

**Comment by pgoldweic** [comment]
I imagine you're most likely right. My question however, still stands. I guess a rephrase of my question is: do you know how long the sdk version currently used in Watson middleware will continue to function (before the API is sunset)? This will tell me how long I have to safely convert my bots to use a newer version of the middleware (before they break in production).

**Comment by pgoldweic** [comment]
Hi @germanattanasio. Glad to hear that you're planning to update the middleware shortly. Thanks!. I was really looking for some official IBM information as to when the removal above would be definitive, so that I can better plan my switch over to your then latest version of this middleware. Sorry if I wasn't clear about this.

**Comment by IgorUehara** [comment]
bot-facebook -> WARNING: Conversation V1 is deprecated and will be removed in the next major release of the SDK. Use Assistant V1 or Assistant V2. Set {silent: true} to disable this message.
