### ISSUE TITLE
Support for API v2

### ISSUE THREAD

**Issue by hosshoss** [watson-developer-cloud/botkit-middleware#156]
Hello Team,

I'm trying to use this plugin to send messages to my Watson assistant and I'm always getting this error : 

```json
{
  "watsonError": {
    "cause": {
      "code": 404,
      "error": "Resource not found",
      "x-global-transaction-id": "ffea405d5bfad94ba8598229"
    },
    "isOperational": true,
    "code": 404,
    "error": "Resource not found",
    "x-global-transaction-id": "ffea405d5bfad94ba8598229"
  }
}
```

I think it may be something related to the API version, my assistant API version is 2 and with the following URL:

Assistant URL: https://gateway.watsonplatform.net/assistant/api/v2/assistants/{assistant-id}/sessions

**Comment by JH-BIG** [comment]
> This library doesn't work with assistant v2. You need to use v1.

I'm in same experience. :(   
because I have poor understanding about coding. It is very hard to make solutions by myself. 
could you give me more detailed instruction about this?  thank you for reading

**Comment by mitchmason** [comment]
If you have a poor understanding of coding, then I would use either the slack or facebook quick deployments that are built into Watson Assistant. Botkit is great for connecting to other channels or doing more complex things because the code is open source.

**Comment by germanattanasio** [comment]
I'm closing this as won't fix.
