### ISSUE TITLE
How to change bot's profile picture on Slack?

### ISSUE THREAD

**Issue by luizj-ibm** [watson-developer-cloud/botkit-middleware#157]
This is the 3rd time I'm writing this post so I'll try to make myself as much clear as possible to prevent people from closing it again without helping.

I'm using this "botkit-middleware" to integrate watson assistant with my slack workspace as the documentation says it does: "easily integrate a Watson Assistant workspace with multiple social channels like Slack".

Despite my watson assistant working fine on bluemix, all the code I have is this "botkit-middleware" from this particular github repository, that's the reason I'm posting my doubt right here.

It's now integrated and working fine. I can talk to my watson assistant via Slack. His name is Slack_Assistant.

How can I replace Slack_Assistant's picture?

Tks

**Comment by germanattanasio** [comment]
@luizj-ibm We don't know how to change a profile picture in Slack, and this is not the place to ask that. *This is a nodejs library that helps you connect Watson Assistant with Slack, Facebook, and other channels.
 
It seems it's working with for you:
> It's now integrated and working fine. I can talk to my Watson assistant via Slack. His name is Slack_Assistant.

Please stop creating issues in this repository.
