### ISSUE TITLE
Resetting the context variables and output

### ISSUE THREAD

**Issue by SaziyaBanu** [watson-developer-cloud/botkit-middleware#159]
Hi,

I am unable to reset the context variables and the output returned in the previous query due to which the results conflict. How can i reset them?
message.watsonData.context = ''; does not seem to work

Thanks in advance

**Comment by SaziyaBanu** [comment]
I am using the same example. I am trying to come out of the child node when the input is invalid and go to exit intent. The intent is detected properly, but the response is not getting updated, resulting in the same child node response.

**Comment by Naktibalda** [comment]
Checking input first would be simpler, than trying to override response later.

**Comment by SaziyaBanu** [comment]
Ok, thank you
