### ISSUE TITLE
Where is the context stored?

### ISSUE THREAD

**Issue by SaziyaBanu** [watson-developer-cloud/botkit-middleware#160]
Hi,

This is not an issue, more of a query.
I would like to know where the context is stored when you say middleware.storage(). Can i have a look into the storage?

Thanks in advance

**Comment by Naktibalda** [comment]
https://botkit.ai/docs/storage.html

**Comment by SaziyaBanu** [comment]
Thanks @Naktibalda 
I got it when I read the documentation link you sent, properly. Thanks a lot again
