### ISSUE TITLE
In case using chat.postmessage with python pg. watson assistant doesn't receive mention.

### ISSUE THREAD

**Issue by kota-jimmny** [watson-developer-cloud/botkit-middleware#161]
I make the python PG which send mention to slack. But by using python PG. mention doesn't transfer to Watson assistant,I know it by checking improve tab. Are there any settings bot kit?

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps.

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
