### ISSUE TITLE
Integrating watson assistant with Whatsapp using twilio and botkit

### ISSUE THREAD

**Issue by developer-bz** [watson-developer-cloud/botkit-middleware#162]
Hi,

Can you please provide me with an example which shows the integration of watson assistant on whatsapp messaging using twilio? Any link or an example would be much helpful.

Thanks in advance

**Comment by germanattanasio** [comment]
Hi @developer-bz We depend on botkit and it looks like they don't have support for WhatsApp yet. See https://github.com/howdyai/botkit/issues/1297

**Comment by developer-bz** [comment]
Thanks @germanattanasio.
