### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by Naktibalda** [watson-developer-cloud/botkit-middleware#171]
[Watson Developer Cloud Node SDK](https://github.com/watson-developer-cloud/node-sdk/blob/master/assistant/v1.ts) (Renamed to [ibm-watson](https://www.npmjs.com/package/ibm-watson) in npm recently) is implemented in Typescript.
The [next version of Botkit](https://github.com/howdyai/botkit/tree/next/packages/botkit/src) is implemented in Typescript too (It will be released in a few weeks time).

I think that it makes perfect sense to implement new major version of this library in Typescript too.

**Comment by germanattanasio** [comment]
Fixed as part of 2.0.0
