### ISSUE TITLE
Is there a WhatsApp step-by-step tutorial similar to FB integration?

### ISSUE THREAD

**Issue by marsrobertson** [watson-developer-cloud/botkit-middleware#193]
Arrived here from: https://www.ibm.com/blogs/watson/2016/11/new-botkit-integration-makes-deploying-watson-bots-messaging-apps-easy/

Arrived there from Google: `ibm ai watson whatsapp`

Is there a WhatsApp step-by-step tutorial similar to FB integration?

https://developer.ibm.com/tutorials/fb-messenger-wcs-botkit/

**Comment by germanattanasio** [comment]
We don't have a WhatsApp tutorial but since we use botkit you can see if someone has a tutorial for it and use it with this library.
