### ISSUE TITLE
TypeError: this.sendToWatson is not a function

### ISSUE THREAD

**Issue by febdev** [watson-developer-cloud/botkit-middleware#200]
I have moved from build 1.8.4 to 2.1.4 to allow new ICP4D token authentication.
Now I am getting this error message below.

`An error occurred in the receive middleware:  TypeError: this.sendToWatson is not a function
    at Ware.<anonymous> (/Users/jinkim/Documents/deckard/deckard/node_modules/botkit-middleware-watson/src/index.ts:177:17)
    at Generator.next (<anonymous>)
    at /Users/jinkim/Documents/deckard/deckard/node_modules/botkit-middleware-watson/lib/index.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jinkim/Documents/deckard/deckard/node_modules/botkit-middleware-watson/lib/index.js:19:12)
    at Ware.receive (/Users/jinkim/Documents/deckard/deckard/node_modules/botkit-middleware-watson/lib/index.js:126:16)
    at Ware.<anonymous> (/Users/jinkim/Documents/deckard/deckard/node_modules/wrap-fn/index.js:75:16)
    at Ware.<anonymous> (/Users/jinkim/Documents/deckard/deckard/node_modules/wrap-fn/index.js:57:27)
    at next (/Users/jinkim/Documents/deckard/deckard/node_modules/ware/lib/index.js:85:20)
    at /Users/jinkim/Documents/deckard/deckard/node_modules/wrap-fn/index.js:121:18`

Nothing has changed on my end except using
`import { WatsonMiddleware } from 'botkit-middleware-watson';`
and changing from
`const watsonMiddleware = require('botkit-middleware-watson')...`
to
`const watsonMiddleware = new WatsonMiddleware(...`
and adding babel preset to allow importing class.

Any idea how to resolve this?

**Comment by Naktibalda** [comment]
You must bind receive method like this now:
```js
controller.middleware.receive.use(
  watsonMiddleware.receive.bind(watsonMiddleware),
);
```

**Comment by febdev** [comment]
Thanks heaps!

**Comment by developer-bz** [comment]
Hi @Naktibalda ,
What if i want to use message filtering with this new method?

Thanks

**Comment by Naktibalda** [comment]
It is exactly the same.

**Comment by developer-bz** [comment]
Do you mean it is the same as below,

const receiveMiddleware = (bot, message, next) => {
  if (message.type === 'direct_message') {
    watsonMiddleware.receive(bot, message, next);
  } else {
    next();
  }
};

slackController.middleware.receive.use(receiveMiddleware);

We don't need to bind receive method? 
Also, if i use the same method as above, it doesn't work.

**Comment by Naktibalda** [comment]
Bind is only necessary if method is passed as parameter in order to allow it to access other fields of middleware.

**Comment by developer-bz** [comment]
It doesn't work as it is. Can you please provide with a sample?

Thanks

**Comment by Naktibalda** [comment]
No, I can't give you another sample.

> It doesn't work as it is.
Please be more specific. Do you get an error or does it do nothing?

The first guess is that a value of message.type is not what you think it is, so do some debugging with `console.log`.
