### ISSUE TITLE
Make sure Watson Assistant context has an expiry value (Redis storage)

### ISSUE THREAD

**Issue by YounesTea** [watson-developer-cloud/botkit-middleware#211]
Hello,

As WA pushes/updates the context in Redis storage via `sendToWatson` and `updateContext`, I need a way to make sure this context TTL is only 24 hours (if the context gets updated, the TTL is updated to 24h again).

I know Redis provides `EXPIRE` and `SETEX` commands, but I'm not sure how to "plug it into" the Watson Botkit Middleware as it is the one storing/updating the context behind the scenes...

Any ideas ?

**Comment by Naktibalda** [comment]
Storage is not a concern of Watson Assistant middleware.

I made pull request to [botbuilder-storage-redis](https://github.com/mokeddes/botbuilder-storage-redis/pull/11), but it hasn't been released yet, so I am using my own fork from private npm repository,.

**Comment by YounesTea** [comment]
@Naktibalda : the TLL is set on the key on both key creation and key update, right ?

**Comment by YounesTea** [comment]
Yes, I realized you make perform a `setex` command
