### ISSUE TITLE
Next() function for receive function

### ISSUE THREAD

**Issue by NxP4Code** [watson-developer-cloud/botkit-middleware#218]
It seems next() is not called in the receive function. Per botKit documentation Next() should be called at the end of receive function to process all middleware stack. 

https://botkit.ai/docs/v0/middleware.html#hear-middleware
> Send and Receive middleware functions are added to Botkit using an Express-style "use" syntax. Each function receives a bot parameter, a message parameter, and a next function which must be called to continue processing the middleware stack.

**Comment by Naktibalda** [comment]
@NxP4Code You are reading documentation of Botkit V0, but comparing it to the latest version of this library.
Watson Botkit middleware 1.* was compatible with Botkit V0 and it called next() in https://github.com/watson-developer-cloud/botkit-middleware/blob/v1/lib/middleware/index.js#L69-L91

**Comment by Naktibalda** [comment]
Up to date documentation is at https://botkit.ai/docs/v4/core.html#middlewares

**Comment by NxP4Code** [comment]
Yes, I noticed V1 of middleware had next() support. It was my mistake that I pasted the link of the BotKit V0 link. Even in V4 BotKit suggest that the signature of middleware should be in the following form

![image](https://user-images.githubusercontent.com/56322272/98821170-c93ad300-23f4-11eb-8d17-8bba290dc1b6.png)
