### ISSUE TITLE
Watson Conversation loses state, resets to root node rather than waiting for user input.

### ISSUE THREAD

**Issue by robert-loredo** [watson-developer-cloud/botkit-middleware#23]
Hello, 

I downloaded and updated the .env file with both my Watson Conversation Service (WCS) creds and my Slack API. 

When I started the simple-bot example it seems to start fine. It receives input from Slack, and it queries WCS and posts a response back to Slack. 

However, I am seeing an issue in one scenario. 
I have a node that asks user for some clarification, the node is set to wait for user response and then continue. 
When I try this on the WCS dialog chat, it works as expected. Context is kept, and the system picks up form the user input and continues on. 
But when I try this from Slack, the user input doesn't seem to start from the node where it is expecting user input, but from the root node. 

Another thing I am noticing which might be related to this issue is that the middleware seems to be pinging WCS. (See console log below) 

`>npm start

> botkit-middleware-watson-simple-example@0.0.1 start /Users/robertloredo/Documents/projects/botkit-demo/examples/simple-bot
> node simple-bot-slack.js

info: ** No persistent storage method specified! Data may be lost when process shuts down.
info: ** Setting up custom handlers for processing Slack messages
info: ** API CALL: https://slack.com/api/rtm.start
Client server listening on port 6002
notice: ** BOT ID: cqs-bot ...attempting to connect to RTM!
notice: RTM websocket opened
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Slack message received!
I `
  
As you can see this is repeating as when I post a slack message it works fine, but after the process is completed, it goes back to looping this message. 

I'm wondering if this is also pinging WCS, if so, then this might be why it is resetting back to root node? 

Any help is appreciated. 

Thank you! 

Robert

**Comment by aarora91** [comment]
@robert-loredo I notice you're using an old version. Can you install the latest 1.1.0 and then try running the example included with it?
We're now advocating the use of the `interpret` function as opposed to the receive function(which was pinging Conversation for _all_ events and not just heard events).
Let me know if that fixes it.

**Comment by robert-loredo** [comment]
Yup! Updating to the latest v1.1 fixed the issue! Thanks! 

One thing I also learned by linking with Slackbot. 
I originally had my WCS on a chat screen. So when client first opened the window, it would send the conversation_start. 
When integrating with Slack, it seems best to not have the conversation_start since the client would just ask it a question right away, (unless of course they send an initial greeting before asking question). Otherwise it would respond with the conversation_start and not the answer to the question. :) 

Thanks again aarora91 ! Happy Holidays!
