### ISSUE TITLE
Intercepting Conversation answer to query database

### ISSUE THREAD

**Issue by clalevee** [watson-developer-cloud/botkit-middleware#24]
I'm trying to develop a bot using botkit-middleware-watson for FB messenger.
Dialog Conversation <-> Messenger runs good.

But now I want to intercept answer from Watson Conversation (event middleware.after ?), query a DB and answer directly to Conversation without using Messenger. Conversation will then interpret/format and answer to the user, using data retrieved from DB.

So my program have to (in event middleware.after ?)
 - receive conversationResponse 
 - query DB, and get answer (son)
 - update Conversation Payload
 - answer to Conversation

Do you have any idea ?

**Comment by stevenoh93** [comment]
You can do this in the _after_ callback as you said, but you'll have to call Conversation on your own.
```javascript
middleware.after = function(message, conversationResponse, callback) {
    // Call db
    mydb.makeQuery(queryString, function(result) {
        payload.context.dataToChange = result;
        conversation.message(payload, function (err, response) {
            callback(null, response);
        });
    });
}
```

**Comment by clalevee** [comment]
here is the test I did : 

`middleware.after = function(message, conversationResponse, callback) {
    
   if (conversationResponse.context) {
         conversation.message({
              workspace_id: process.env.WORKSPACE_ID,
              input: {'text': 'Test message'},
              context: conversationResponse.context
         }, function (err, response) {
               if (err)
                  console.log('error:', err);
               else
                  console.log(JSON.stringify(response, null, 2));
               callback(null, response);
         });
   }
   else callback(null, conversationResponse);

} `

But, I don't receive any answer from Conversation or see log message in console...
Is  conversation (in "conversation.message" function) can be use outside of botkit middleware ?

**Comment by clalevee** [comment]
It's better, it nearly works, I can call Conversation and receive a new payload
My new code

```
 middleware.conversation.message({
                          workspace_id: process.env.WORKSPACE_ID,
                          input: {'text': 'SQL100'},
                          context: conversationResponse.context
                     }, function (err, response) {
                           if (err)
                              console.log('error:', err);
                           else {
                             console.log("Generated anwser ");
                             console.log(response);
                             callback(null, response);
                           }
 });
```
But, even if _response_ seems good ( _console.log(response)_ ), the callback doesn't generate an answer to Messenger.

**Comment by clalevee** [comment]
[INFO]
This app is running on Bluemix.
To be able to detect that _conversation.message_ is not defined, I had to add Try-Catch.

**Comment by stevenoh93** [comment]
Is there no response coming back on Messenger or are you getting something outdated?

If you want to change the response that's being sent back to Messenger, you have to update the `message` object passed in as a parameter. So right before the callback, you'd want to do this:
```
message.watsonData = response;
```

**Comment by clalevee** [comment]
I was something outdated..
So, I added _message.watsonData = response_ before callback as mentioned and it works !!

```
middleware.conversation.message({
                          workspace_id: process.env.WORKSPACE_ID,
                          input: {'text': 'SQL100'},
                          context: conversationResponse.context
                     }, function (err, response) {
                           if (err) {
                              console.log('error:', err);
                              ....
                            }
                           else {
                             console.log("Generated anwser ");
                             console.log(response);
                             message.watsonData = response;
                             callback(null, response);
                           }
 });
```

Now, i just have to really call DB.
Thx for your rapid and high quality assistance.
