### ISSUE TITLE
Intercepting Conversation answer to query database - lost of context ?

### ISSUE THREAD

**Issue by clalevee** [watson-developer-cloud/botkit-middleware#26]
Following issue #24...

Scenario: 
intercept answer from Watson Conversation (event middleware.after), query a DB and answer directly to Conversation without using Messenger. Conversation will then interpret/format and answer to the user, using data retrieved from DB.

So my program does:
- receive conversationResponse in event middleware.after
- query DB, and get answer 
- update Conversation Payload with DB result
- answer to Conversation / receive Conversation answer
- call callback to answer to user (Messenger)

In Conversation simulator, it works fine, but not in this program.
It seems that the call of middleware.conversation.message (after DB call) increments dialog_turn_counter (and it's OK) but the callback reset  dialog_turn_counter to the value before the call of middleware.conversation.message. 

See code & trace in PDF.

[Issue_BotKit.pdf](https://github.com/watson-developer-cloud/botkit-middleware/files/693095/Issue_BotKit.pdf)

**Comment by stevenoh93** [comment]
Thanks for the detailed report! This was fixed in our latest push, so if you update your local module to the latest version, you shouldn't see this problem anymore.

**Comment by clalevee** [comment]
I updated my package.json file to use new module version, push to Bluemix and it works !

`
  "botkit-middleware-watson": "^1.2.0"

`
Thx
