### ISSUE TITLE
Localtunnel issue

### ISSUE THREAD

**Issue by hakey1408** [watson-developer-cloud/botkit-middleware#37]
i'm having an issue with localtunnel and botkit. I setup all the correct fields in the .env file (USE_FACEBOOK=true, watsonID, PSW, etc...).
I open the cmd and type 

> 'lt --s watsontyres --p 5000'

 where watsontyres is my appname, the reply is 

> 'your url is: https://watsontyres.localtunnel.me'.

I type 'node server.js' and:

> _info: ** No persistent storage method specified! Data may be lost when process shuts down.
> info: ** Serving webhook endpoints for Messenger Platform at: http://MY_HOST:undefined/facebook/receive
> Facebook bot is live
> Client server listening on port 5000_

So i think the problem is here, because it doesn't show the correct url.
Next i go on facebook dev page and when i try to setup the webhook it says 502 bad gateway.
Can you help me solving this problem please?

**Comment by stevenoh93** [comment]
Hi,

The url printed in the console is not an accurate log, so I wouldn't worry about it (it's botkit's hard coded log). I also wouldn't worry about the persistent storage warning unless you're beyond prototyping phase.
Couple things to consider about the 502 error:

- Make sure you use the full path: https://watsontyres.localtunnel.me/facebook/receive
- See what's printing in the console. It may be some internal error

Hope this helps

**Comment by hakey1408** [comment]
Hi steven,
I put in facebook webhooks the fullpath you wrote the first time too. This is the error that FB report when i click on 'save' : 

> Callback verification failed with the following errors: HTTP Status Code = 502; HTTP Message = Bad Gateway.

Where can i find the errors printed in the console? if you mean the cmd here it is:

> C:\Users\e.tomaello\Dropbox\BlueIT\DeployFB\botkit-middleware-master\examples\multi-bot>lt --s watsontyres --p 5000
your url is: https://watsontyres.localtunnel.me

> C:\Users\e.tomaello\Dropbox\BlueIT\DeployFB\botkit-middleware-master\examples\multi-bot>node server.js
> info: ** No persistent storage method specified! Data may be lost when process shuts down.
> info: ** Serving webhook endpoints for Messenger Platform at: http://MY_HOST:undefined/facebook/receive
> Facebook bot is live
> Client server listening on port 5000

**Comment by stevenoh93** [comment]
Okay, just doing a couple sanity checks:
Is there nothing else in the console (yes, I do mean the cmd) _after_ you tried to verify with Facebook?
Also, are you sure localtunnel is up at the same time as the app is running on another cmd?
If that's all true, my best guess is that the windows firewall may be blocking the connection.

**Comment by hakey1408** [comment]
Thank you steven!
Probably the place where i study was blocking localtunnel, i tried right now at home and works like a charm.
Now the console prints something too every time i write a message.
