### ISSUE TITLE
Link to new Slack Bot instructions is 404

### ISSUE THREAD

**Issue by remkohdev** [watson-developer-cloud/botkit-middleware#41]
https://github.com/howdyai/botkit/blob/master/readme-slack.md

this link in the https://github.com/watson-developer-cloud/botkit-middleware/README doesnt exist
"Otherwise, follow <a>Botkit's instructions</a> to create your Slack bot from scratch. When your bot is ready, you are provided with a Slack token."

**Comment by remkohdev** [comment]
Should be
https://github.com/howdyai/botkit/blob/master/docs/readme-slack.md
with /docs/...

**Comment by germanattanasio** [comment]
Hey @remkohdev do you mind writing a PR ?
