### ISSUE TITLE
How use templates for Facebook?

### ISSUE THREAD

**Issue by azanoni** [watson-developer-cloud/botkit-middleware#45]
Hi, I want to if the botkit support templeats, and how we need to attachment in some callback?

https://developers.facebook.com/docs/messenger-platform/send-api-reference/templates

I saw this example: 

https://github.com/howdyai/botkit/blob/master/docs/readme-facebook.md

But I dont know if botkit have it, and how need to implement.

Thanks

**Comment by mitchmason** [comment]
Your best bet will be to examine the botkit github. We only wrote a middleware to connect botkit to Watson, but Botkit owns the functionality.

**Comment by azanoni** [comment]
I find it where... You can add here https://github.com/watson-developer-cloud/botkit-middleware/blob/master/examples/multi-bot/bot-facebook.js , any functions that are for example here: https://github.com/howdyai/botkit/blob/master/docs/readme-facebook.md
