### ISSUE TITLE
slack teams lookup > 20 times/second?

### ISSUE THREAD

**Issue by monte-hayward** [watson-developer-cloud/botkit-middleware#47]
Can this issue be addressed in botkit-middleware?
https://github.com/howdyai/botkit/issues/847
Seems like it might be triggered by utils.js / readContext and friends.

**Comment by germanattanasio** [comment]
This should be fixed in botkit. We use botkit to abstract the code for the different user channels(Facebook, Slack, Twilio, etc...). Writing a cache for Slack should be a requirement for botkit and not this library.
