### ISSUE TITLE
Send two responses for one request from facebook

### ISSUE THREAD

**Issue by vishwasrao** [watson-developer-cloud/botkit-middleware#51]
Hi,
I am using this middleware to integrate watson conversation and facebook messanger.
I have specific requirement that.
When user is asking near by location then need send:
1. First response will be " Let me find these locations for you"
2. Second response will be after few seconds (1-2), with actual results from external api call.

Is there any way to handle this?

Thanks,
Vishwas

**Comment by Naktibalda** [comment]
@vishwasrao I've only used a new Socket connector, but it should be the same with Facebook.

If you do action processing in `controller.on('message_received'` callback, you can call `bot.reply` before and after API call.

**Comment by germanattanasio** [comment]
I think @Naktibalda addressed the question so I'm going to close this issue for now.
