### ISSUE TITLE
How do I implement before: and after: methods in a SLACK bot

### ISSUE THREAD

**Issue by jjdepaul** [watson-developer-cloud/botkit-middleware#52]
New to Node.js and not sure how to make use of these methods in a simple SLACK bot....  I want to call an external service to fetch data based on context variables from the conversation.  THe variables are there now, I can see them coming across.   
Questions:
1)  How do I make use of these methods?!  
2)  Are these methods asynchronous?
3)  How do I get Watson conversation context into these methods so I can pull the parameters passed in?

A small example would be much appreciated, plz.

```
slackController.hears(['.*'], ['direct_message', 'direct_mention', 'mention'], function(bot, message) {
	  slackController.log('Slack message received');
	  //middleware.before(bot, message, function(beferr) {
		    //	  console.log('Inside the before method.  messageB=' + JSON.stringify(message, 2, null));
			//});
	  middleware.interpret(bot, message, function(err) {
	    if (!err)
			  bot.reply(message, message.watsonData.output.text.join('\n'));
	          console.log('**********>message.watsonData.context=' + JSON.stringify(message.watsonData.context, 2, null));
	          //console.log('message.watsonData.output=' + message.watsonData.output.text.join('\n'));
		});
	 // middleware.after(bot, message, function(afterr) {
		 //   	console.log('Inside the after method.  messageA=' + JSON.stringify(message, 2, null));
		
```

**Comment by vishwasrao** [comment]
@jjdepaul 

1. How do I make use of these methods?! <Vishwas> As mentioned in readme, you can use these methods to do some operations before sending it to Conversation or after getting response from conversation.
2. Are these methods asynchronous? <Vishwas> yes , these methods are async, You are using NodeJS .
3. How do I get Watson conversation context into these methods so I can pull the parameters passed in?
<Vishwas> find below code snippet to get idea.
Also you can refer multi-bot example which gives basic idea to get started.


```
 // Customize your Watson Middleware object's before and after callbacks.
  middleware.before = function(message, conversationPayload, callback) {
  //Passing values to conversation.
  conversationPayload.context = USER_DETAILS;
  conversationPayload.context.timezone = $TIME_ZONE;
    callback(null, conversationPayload);
  }

  middleware.after = function(message, conversationResponse, callback) {
  //You set context variable in convrsation and using it here
   if(conversationResponse.context.Flag)
    {
	Do some stuff
	}
    callback(null, conversationResponse);
  }
```

Hope this helps.

Thanks,
Vishwas

**Comment by jjdepaul** [comment]
Thank you Vishwas - it helps me a lot.  So now my middleware.after method looks like this:

`	  middleware.after = function(message, conversationResponse, callback) {
		    if (conversationResponse.context) {
		        	  		console.log("*****************  Calling external service to get data!!! *****************");
		        	  		// clearing vars after the call
		        	  		conversationResponse.context.topic = "";
		        	  		// Notify the user of External service call
                                                Function to call remote Server {} 
		        	  		conversationResponse.output.text[1] += '\nCalling external service for you now... :zap:';
		   } 
		    callback(null, conversationResponse);
	 }
`
Suppose I then call a remote server that will query some data and want to display the results back to the user....    how could I send that message back to the SLACK user?!   It seems that the data may arrive long after I have responded to the user..... What object do I used then to send data to SLACK?

**Comment by germanattanasio** [comment]
@jjdepaul you need to use callbacks or promises and wait for the response to your API before sending the message back to slack.
