### ISSUE TITLE
Using temporary storage

### ISSUE THREAD

**Issue by Lopics** [watson-developer-cloud/botkit-middleware#54]
I'm using simple-bot and my bot keeps restarting conversation rather continuing on the same one (Creating new session everytime a message is sent). Additionally, it would reply with a dialog with given intents (such as #intent) and would ignore welcome and anything_else dialogs.

Tried run as administrator.

info: ** No persistent storage method specified! Data may be lost when process shuts down.
info: ** Setting up custom handlers for processing Slack messages
info: ** API CALL: https://slack.com/api/rtm.start
Client server listening on port 5000
notice: ** BOT ID: test ...attempting to connect to RTM!
notice: RTM websocket opened
info: Slack message received
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Slack message received
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Slack message received
info: Slack message received
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Slack message received
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Slack message received
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Slack message received
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Slack message received
info: Warning: using temporary storage. Data will be lost when process restarts.
info: Slack message received
info: Warning: using temporary storage. Data will be lost when process restarts.

**Comment by germanattanasio** [comment]
The message is clear. You need to specify a storage otherwise the data will be lost when the process running the bot restarts.
