### ISSUE TITLE
[Feature request] Export updateContext function

### ISSUE THREAD

**Issue by Naktibalda** [watson-developer-cloud/botkit-middleware#56]
In my project, when Conversation returns `output.action = 'something'`,  I want to store the result of action in context storage.

Currently the only way to access updateContext function is by using
```js
var watsonUtils = require('./node_modules/botkit-middleware-watson/lib/middleware/utils.js');
watsonUtils.updateContext(
    message.user,
    watsonMiddleware.storage,
    {
        context: context
    },
    callback
);
```
I have been told that the code would become even uglier if I wanted to use it in a library.

It would be much more convenient to use it if I could call `watsonMiddleware.updateContext`.

**Comment by Naktibalda** [comment]
I figured out how to update context in `middleware.after` and send message in `controller.on`.
It is certainly more elegant than doing everything in `controler.on`,
however it is impossible to send replies from `middleware.after`, so bot can't send `Please wait while ...` message before performing a slow action.

I will make a PR of updateContext with a good example in README next week.

**Comment by germanattanasio** [comment]
Thanks for your help with the library @Naktibalda ! 🎉
