### ISSUE TITLE
[Docs] What's the point of interpret() function?

### ISSUE THREAD

**Issue by Naktibalda** [watson-developer-cloud/botkit-middleware#58]
I read README down to the bottom for the first (or maybe second) time now.

Documentation says that `interpret` is somehow different from `receive` when it clearly is just a copy.
https://github.com/watson-developer-cloud/botkit-middleware/tree/master#interpret
The whole section looks misleading to me. "mapping" and "triggering" is a choice of developer who integrates watson middleware to botkit. `Interpret` can be used as middleware, and `receive` can be called from controller.

I think that instead of documenting functions, it would be better to have a feature section like "Call Conversation for selected messages only", which should advice to not to register middleware and call function from controller.

**Comment by germanattanasio** [comment]
Can you write a PR?

**Comment by Naktibalda** [comment]
I updated README in #66
