### ISSUE TITLE
How to send the empty message to Watson when a new session is created

### ISSUE THREAD

**Issue by Naktibalda** [watson-developer-cloud/botkit-middleware#61]
All bot [examples ](https://www.ibm.com/watson/developercloud/doc/conversation/develop-app.html#communicating-with-the-conversation-service)in Developer Cloud start with
```
// Start conversation with empty message.
conversation.message({}, processResponse);
```

It triggers `conversation_start` event in Conversation.

However [this code](https://github.com/watson-developer-cloud/botkit-middleware/blob/v1.3.1/lib/middleware/index.js#L119-L127) in middleware makes middleware ignore empty messages.

Is there a workaround?

Actually there is a bug in that code - it doesn't call return after callback, so execution continues and the message is sent to Watson Conversation anyway, but the answer is ignored.

**Comment by causapolis1** [comment]
Just use `callback function` (()) . The first question did you mean setTimeout?
Use next() to pass throught the function anyway,  if not, will load an async.
put in .json file other packages. Mocha and Lodash is fine.
Maybe nodemon as CI `(lodash)‘;
This is the way I did and it worked.
