### ISSUE TITLE
Using Conversation in new Frankfurt region

### ISSUE THREAD

**Issue by clalevee** [watson-developer-cloud/botkit-middleware#74]
trying to use a Conversation service, instantiated in the new Bluemix Frankfurt region, I received following message:

`Fatal TypeError: Cannot read property 'output' of undefined`

It seems that new region not yet supported by WDC SDK.
Workaround:

- add new parameter in .env file
`CONVERSATION_URL=https://gateway-fra.watsonplatform.net/conversation/api`

- take this parameter in account in app.js
```
var middleware = require('botkit-middleware-watson')({
  username: process.env.CONVERSATION_USERNAME,
  password: process.env.CONVERSATION_PASSWORD,
  workspace_id: process.env.WORKSPACE_ID,
  url: process.env.CONVERSATION_URL || 'https://gateway.watsonplatform.net/conversation/api' , 
  version_date: '2016-09-20'
});
```

Is it the best way ? another suggestion ?

**Comment by Naktibalda** [comment]
Thanks, this information was useful to me.
You approach looks good.

**Comment by Naktibalda** [comment]
@germanattanasio I think that this issue can be closed.
