### ISSUE TITLE
Waston output text is empty

### ISSUE THREAD

**Issue by Nijinsha** [watson-developer-cloud/botkit-middleware#80]
```js
{ type: 'message',
  channel: 'C6ESXUD2T',
  user: 'U6F4JLZ2T',
  text: 'hello',
  ts: '1501606591.751190',
  source_team: 'T6ESXU955',
  team: 'T6ESXU955',
  watsonData: { intents: [],
     entities: [],
     input: { text: 'hello' },
     output:
      { text: [],
        nodes_visited: [],
        warning: 'No dialog node matched for the input at a root level. (and there is 1 more warning in the log)',
        log_messages: [Array] },
     context:
      { conversation_id: '72af1b06-ec67-43e2-b5bf-73fa0e570ae6',
        system: [Object] } },
  event: 'ambient',
  match: [ 'hello', index: 0, input: 'hello' ] }`
```
do I have to do anything in watson dashboard?

**Comment by germanattanasio** [comment]
This issue is not clear. What are you trying to do? What's the problem? Which version are you using? Can you add some steps to reproduce the issue? Maybe a code snippet.

**Comment by mitchmason** [comment]
The error in the output.warning section says there is no node that matched to your input. typically this is because you have some jump to's causing an infinite loop so it never falls to anything_else. This is an issue with your dialog design, without a screenshot I cant say exctly what.

**Comment by germanattanasio** [comment]
Not an issue with this library.
