### ISSUE TITLE
readme file typo in sample code - needs correction

### ISSUE THREAD

**Issue by pgoldweic** [watson-developer-cloud/botkit-middleware#81]
Thanks for sharing this useful middleware!. Just getting started with it, and I noticed that your section entitled 'Using updateContext in controller (available since v1.4.0)' has a function called 'checkBalance' that is using an undefined 'watsonResponse' variable (apparently defined in the previous example, since it was one of the original parameters of that function). Hope you can correct it when you have a chance. Thanks!

**Comment by Naktibalda** [comment]
Thanks for reporting.
