### ISSUE TITLE
Error: Could not verify message was sent by facebook

### ISSUE THREAD

**Issue by jerinsj** [watson-developer-cloud/botkit-middleware#84]
Was able to setup webhook, facebook bot is live but when I sent a message to the bot this is what I see. Any idea how to resolve this issue?
![capture](https://user-images.githubusercontent.com/16564697/29197433-5ae199aa-7e09-11e7-85bb-4668cf947839.PNG)

**Comment by mitchmason** [comment]
Are you running this locally? 
Did you set up local tunnel and point it at port 5000?
Im not super familiar with all of botkits error codes, so just covering the basics first.

**Comment by jerinsj** [comment]
Yes I am running this locally and yes local tunnel was set up port 5000.... as shown in the picture the client server is listening on port 5000, webhook was set up and it even said the hub.verify token but when I try to message the bot it doesn't reply instead the error in the picture is what I see...

**Comment by jerinsj** [comment]
I followed as shown here in this youtube video https://www.youtube.com/watch?v=FdsjS7ZnPLw&t=406s
except instead of using the car bot example I used my own...

**Comment by mitchmason** [comment]
I'm not sure who that is that made that video, but I'm sure we can work this out. My next best guess would be that your verify token is not matching, hence why the error says 'cannot verify coming from facebook' so that seems like a logical place to double check. Make sure your app secret, verification token, and access token are all correct.

**Comment by germanattanasio** [comment]
Closed due to inactivity. Feel free to open if this is still an issue.

**Comment by ehaynie63** [comment]
I am having the exact same issue. Already double checked the verify token, secret key etc. I have a feeling the video we watched may have skipped some of the first steps..
