### ISSUE TITLE
ERROR: message.watsonError is seen 

### ISSUE THREAD

**Issue by seosuho** [watson-developer-cloud/botkit-middleware#85]
Hello,

I tried to connect Facebook Bot to Watson conversation.
So I referenced below site.
https://www.youtube.com/watch?v=FdsjS7ZnPLw

But In my case, Watson message error is seen. Below is my source code.
============================================================== 
controller.hears('(.*)','message_received', function (bot, message) {
    console.log("message.watsonError" + message.watsonError);
    if (message.watsonError) {
        bot.reply(message, "I'm sorry, but for technical reasons I can't respond to your message");
    } else {
        bot.reply(message, message.watsonData.output.text.join('\n'));
    }
});
==============================================================
In my console, If I print "message.watsonError" variable, the result is "message.watsonErrorError: Forbidden".

It would be helpful, if you give me some idea. 
Thanks you.

**Comment by jerinsj** [comment]
what did you do to fix the error?
