### ISSUE TITLE
ERROR: message.watsonError is seen

### ISSUE THREAD

**Issue by seosuho** [watson-developer-cloud/botkit-middleware#86]
Hello,

I tried to connect Facebook Bot to Watson conversation.
So I referenced below site.
https://www.youtube.com/watch?v=FdsjS7ZnPLw

But In my case, Watson message error is seen. Below is my source code.

```js
controller.hears('(.*)','message_received', function (bot, message) {
  console.log("message.watsonError" + message.watsonError);
  if (message.watsonError) {
    bot.reply(message, "I'm sorry, but for technical reasons I can't respond to your message");
  } else {
    bot.reply(message, message.watsonData.output.text.join('\n'));
  }
});
```

Although I can see text message in facebook messenger like "I'm sorry, but for technical reasons, I can't respond to your message", I can't see Watson Data.
In my console, If I print "message.watsonError" variable, the result is "message.watsonErrorError: Forbidden".
For Reference, I already applied watson `CONVERSATION_USERNAME`,  `CONVERSATION_PASSWORD`, `WORKSPACE_ID`, `CONVERSATION_URL` to `.env` file.  

It would be helpful if you give me some idea.
Thank you.

**Comment by Naktibalda** [comment]
I've checked what errors are returned when invalid values are set to different environment variables
and it appears that Forbidden is returned when CONVERSATION_URL ends with incorrect path.

`CONVERSATION_URL` must end with `/conversation/api`.

**Comment by Naktibalda** [comment]
@seosuho have you figured it out?

**Comment by germanattanasio** [comment]
Closed due to inactivity. I agree with @Naktibalda, the error is probably on the environment variables.
