### ISSUE TITLE
replyWithTyping function

### ISSUE THREAD

**Issue by emrhio** [watson-developer-cloud/botkit-middleware#87]
Hi,

I'm using this middleware to connect watson conversation with fb messenger, but when i try to use replyWithTyping i get the error:
`bot.replyWithTyping is not a function`  and with
`bot.reply` everything works fine

Could you help me with this? thanks

**Comment by Naktibalda** [comment]
I don't think that it is an issue of middleware.

a) Are you really using facebookbot? Methods are inconsistent across different "bots" in botkit.
b) What version of botkit have you got there? replyWithTyping was added to facebookbot in v4.0.

If you are actually using facebookbot and a recent version of botkit, please provide some code.

**Comment by emrhio** [comment]
My bad, thought i was using the last version of botkit. It works perfectly.
