### ISSUE TITLE
Conversation ends abruptly....

### ISSUE THREAD

**Issue by jjdepaul** [watson-developer-cloud/botkit-middleware#90]
I'm using these in my sample work:
    "botkit": "^0.5.8",
    "botkit-middleware-watson": "^1.4.0"

My conversation is very simple, it asks three questions of the user to collect enough data to run a query.  The conversation starts fine, goes to the Billing branch and then to the Aggregate branch just like it should, but then it falls out to 'Anything Else' instead of staying in the conversation path to the end - please see attached diagram below.

My agent code is down below.   Please advise what is missing, I can see the conversation counter advancing each time.... why does the conversation end abruptly?

![conversation ends abruptly](https://user-images.githubusercontent.com/13757467/29848588-dc9185e4-8cde-11e7-876b-cc941531d30c.png)

Here is my agent code:
```javascript
require('dotenv').load();

var Botkit = require('botkit');
var express = require('express');

// Configure your bot.
var slackController = Botkit.slackbot();
var slackBot = slackController.spawn({
  token: process.env.SLACK_TOKEN
});

// Create the middleware object - for connecting with conv.
var watsonMiddleware = require('botkit-middleware-watson')({
  username: process.env.CONVERSATION_USERNAME,
  password: process.env.CONVERSATION_PASSWORD,
  workspace_id: process.env.WORKSPACE_ID,
  url: process.env.CONVERSATION_URL || 'https://gateway.watsonplatform.net/conversation/api',
  version_date: '2017-05-26'
});

// This declares the watsonMiddleware as the handler for the receive method
slackController.middleware.receive.use(watsonMiddleware.receive);


slackController.hears(['.*'], ['direct_message'], function(bot, message) {
  watsonMiddleware.interpret(bot, message, function() {
    if (message.watsonError) {
      bot.reply(message, "I'm sorry, but for technical reasons I can't respond to your message");
    } else {
      console.log("\nsprint-bot-slack.js > to the bot with message.context: " + JSON.stringify(message.watsonData.context, 2, null) + "\n");
      bot.reply(message, message.watsonData.output.text.join('\n'));
    }
  });
}); 

// Start the bot using Real Time Messaging APIs
slackBot.startRTM();
```

**Comment by Naktibalda** [comment]
It is highly unlikely that this is an issue of Botkit Watson Middleware.
Most likely it is an issue of your dialogue.

Better places to ask such questions are:
https://developer.ibm.com/answers/topics/watson-conversation/
https://stackoverflow.com/questions/tagged/watson-conversation
http://wdc-slack-inviter.mybluemix.net/

Your screenshot makes an impression that `Aggregate` is the last node in the chain and the next message sent by the user triggers top level recognition again. It is a [normal behaviour](https://console.bluemix.net/docs/services/conversation/dialog-build.html#dialog-flow).
If you don't want to go back to beginning at the end of the chain, you have to change the action from `Wait for user input` to `Jump to ...`

**Comment by germanattanasio** [comment]
Not a issue with this library
