### ISSUE TITLE
TypeScript definition file

### ISSUE THREAD

**Issue by Naktibalda** [watson-developer-cloud/botkit-middleware#93]
Botkit has got a Typescript definition file [recently](https://github.com/howdyai/botkit/blob/master/lib/Botkit.d.ts).
It would be good to create a definition file for Watson middleware too.
Is it OK to add it to this repo?

**Comment by germanattanasio** [comment]
Yeah

**Comment by Naktibalda** [comment]
I have the definition code, but I will only make a PR when other PRs are merged, because they affect interface of the library.
