### ISSUE TITLE
Unable to set web hooks with Facebook

### ISSUE THREAD

**Issue by VishalWaman** [watson-developer-cloud/botkit-middleware#97]
When i try to set webhook.. I get below message

> The URL couldn't be validated. Response does not match challenge, expected value="162324691", received="OK"

![1](https://user-images.githubusercontent.com/20675961/30239912-8c739eb4-9583-11e7-9081-3793b4a19073.png)

**Comment by Naktibalda** [comment]
Your issue has nothing to do with Watson middleware.

**Comment by VishalWaman** [comment]
Yes, this was configuration issue its fixed. Closing..
